language: cpp
git:
  submodules: true
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    addons:
      apt:
        packages:
        - libjack-dev
        - liblhasa-dev
        - librtmidi-dev
        - libsdl2-dev
        - libzzip-dev
    script: &cmake_build
    - mkdir build
    - pushd build
    - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 ..
    - cmake --build .
    - cpack
    - popd
  - os: osx
    addons:
      homebrew:
        packages:
        - xmlto
    before_install:
    - pushd resources/pictures/docicons/osx
    - wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/docerator/docerator-2.0.zip
    - unzip docerator-2.0.zip -d docerator
    - rm docerator-2.0.zip
    - "/usr/bin/python genicons.py"
    - popd
    script: *cmake_build
deploy:
  provider: releases
  api_key:
    secure: "tuoM4T5yYeqtmqjK5m9+zsVkLYqfwD/Lf5nyXPaONDRvgo7lh46OvNXPcHCu4QK6j80PmmzvhK/B0L836puEQpcaKsksdO8WTp3Lw4wPiidOC30rw+OR9jDnJzbPmv+PXxmqENIDUccLhDKpB9IGfosgcaxERvlvJZ44XlHnmgIPhXrKlESDnrV44snFJ/JkjlcNJr55nOdbCHTEUrW3J+kkYqjA3kyMW9/rS+iWx2PRLYKUBQDh+7U6frEjI8E4Ygpr5L6Cm7T2SuOWJhp+8tu9fEDZtfCngrU8ZTYclgAIqCyh1o6BU9ljcpU26CBcDYnNcqeFV8a7GcK/D32ix26rMvff9Ngei2uWs9ZYTGSSSC8CGnVpfPxi2ZSN15/pvqxhwr6I5Z/V/RX5+ZjdAyU6IIHo7GGt2y/e/zkoxfOBeiv1EV+gPZPbKafKkDX1Xghxp8t64qXynMctKiM3KCbcLRi+Z0Srym+lrIHYY2jo/cWk88VK6xGjCk5SDtQlkJgxN72Jbyy4kWMPIa7aOzrSA9WbUXG26osw38sNIGe5Rs1pErvSKMV3slLWBBDtzvh1Z/zUO34W6FyKilBwoE3zTvE/lnAZtBWyk0QCNxJvLReqNGZE53Zk8VuGmBQ9S9aIXqm21CSuEYVpvhogXAj82ePNH9Dy3B4A0KIqUBY="
  skip_cleanup: true
  file_glob: true
  file: build/milkytracker-*
  on:
    repo: milkytracker/MilkyTracker
    tags: true
